/** Re-export shared weight-loss BMI eligibility rules for the patient app. */
export {
  BMI_THRESHOLD_BAME,
  BMI_THRESHOLD_COMORBIDITY,
  BMI_THRESHOLD_WHITE,
  MOUNJARO_STARTER_DOSE_MG,
  WEGOVY_STARTER_DOSE_MG,
  computeBmiFromMetrics,
  evaluateWlBmiEligibility,
  getApplicableBmiThresholds,
  getBmiEligibilityThreshold,
  hasWlComorbidity,
  isBameEthnicity,
  isMounjaroAboveStarterDose,
  isWegovyAboveStarterDose,
  isWhiteEthnicity,
  isWlPriorProviderPatient,
  isWlStarterDoseRequested,
  maxRequestedMounjaroDoseMg,
  maxRequestedWegovyDoseMg,
  patientMeetsBmiEligibility,
  requiresPreviousBmiVerification,
  requiresPreviousPrescription,
  resolveConsultationBmi,
  wlBmiEligibilityAnswerFields,
  type WlBmiEligibilityOutcome,
} from "@workspace/evidence-slots";
