import { Router, type IRouter } from "express";
import healthRouter from "./health";
import conditionsRouter from "./conditions";
import consultationsRouter from "./consultations";
import dashboardRouter from "./dashboard";
import authRouter from "./auth";
import patientRouter from "./patient";
import patientNotesRouter from "./patient-notes";
import consultationNotesRouter from "./consultation-notes";
import complianceRouter from "./compliance";
import productsRouter from "./products";
import ordersRouter from "./orders";
import commsRouter from "./comms";
import patientTimelineRouter from "./patient_timeline";
import paymentsRouter from "./payments";
import notificationsRouter from "./notifications";
import consultationMessagesRouter from "./consultation-messages";
import prescriptionPdfRouter from "./prescription-pdf";
import pharmacistPatientsRouter from "./pharmacist-patients";
import messageThreadsRouter from "./message-threads";
import pharmacistPushTokensRouter from "./pharmacist-push-tokens";
import seoRouter from "./seo";
import patientAccountRouter from "./patient-account";
import pharmacistToolsRouter from "./pharmacist-tools";
import auditLogRouter from "./audit-log";
import pharmacistSettingsRouter from "./pharmacist-settings";
import gpPracticesRouter from "./gp-practices";
import postcodesRouter from "./postcodes";
import pmrScanRouter from "./pmr-scan";
import pmrWorkflowRouter from "./pmr-workflow";

const router: IRouter = Router();

router.use(authRouter);
router.use(healthRouter);
router.use(conditionsRouter);
router.use(consultationsRouter);
router.use(dashboardRouter);
router.use(patientRouter);
router.use(patientNotesRouter);
router.use(consultationNotesRouter);
router.use(complianceRouter);
router.use(productsRouter);
router.use(ordersRouter);
router.use(commsRouter);
router.use(patientTimelineRouter);
router.use(paymentsRouter);
router.use(notificationsRouter);
router.use(consultationMessagesRouter);
router.use(prescriptionPdfRouter);
router.use(pharmacistPatientsRouter);
router.use(messageThreadsRouter);
router.use(pharmacistPushTokensRouter);
router.use(seoRouter);
router.use(patientAccountRouter);
router.use(pharmacistToolsRouter);
router.use(auditLogRouter);
router.use(pharmacistSettingsRouter);
router.use(gpPracticesRouter);
router.use(postcodesRouter);
router.use(pmrScanRouter);
router.use(pmrWorkflowRouter);

export default router;
